---
title: "Visualization"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
library(p8105.datasets)

data("weather_df")
```

Now we have everything we need! 

Start with a scatterplot. 

```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point() + 
  labs(
    title = "Temperature (Max vs Min)",
    x = "Max Temperature (C)",
    y = "Min Temperature (C)",
    color = "Location",
    caption = "Data from NOAA"
  )
```

Let's try some other scales. 

```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point() + 
  labs(
    title = "Temperature (Max vs Min)",
    x = "Max Temperature (C)",
    y = "Min Temperature (C)",
    color = "Location",
    caption = "Data from NOAA"
  ) + 
  scale_x_continuous(
    breaks = c(-10, 0, 15),
    labels = c("10 C", "0", "Fiftenn")
  ) + 
  scale_y_continuous(
    trans = "sqrt",
    position = "right"
  )
```


```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point() + 
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  )
```

## Themes

```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point() + 
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) + 
  theme(
    legend.position = "bottom"
  ) + 
  theme_minimal()
```


```{r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) + 
  theme(
    legend.position = "bottom"
  ) + 
  theme_minimal()
```

## Two more weird but useful plot things
```{r}
central_park_df = 
  weather_df |> 
  filter(name == "CentralPark_NY")

molakai_df = 
  weather_df |> 
  filter(name == "Molokai_HI")

ggplot() + 
  geom_point(molakai_df, mapping = aes(x = date, y = tmax, color = name)) + 
  geom_line(central_park_df, mapping = aes(x = date, y = tmax, color = name))
```


```{r}
ggp_tmax_tmin = 
  weather_df |> 
  ggplot() + 
  geom_point(mapping = aes(x = tmin, y = tmax, color = name)) + 
  theme(legend.position = "none")

ggp_prcp_density = 
  weather_df |> 
  filter(prcp > 0) |>
  ggplot(mapping = aes(x = prcp, fill = name)) + 
  geom_density(alpha = 0.5) + 
  theme(legend.position = "none")

ggp_seasonal = 
  weather_df |> 
  ggplot(mapping = aes(x = date, y = tmax, color = name)) + 
  geom_point()

(ggp_tmax_tmin + ggp_prcp_density) / ggp_seasonal
```

## Data manipulation

Start with factors. 

```{r}
weather_df |> 
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |>
  ggplot(mapping = aes(x = name, y = tmax)) + 
  geom_boxplot()
```

Make the distribution plots 

```{r}
weather_df |> 
  select(name, tmax, tmin) |> 
  pivot_longer(
    tmax:tmin, 
    names_to = "observation",
    values_to = "temp"
  ) |> 
  ggplot() + 
  geom_density(mapping = aes(x = temp, fill = observation), alpha = 0.5) + 
  facet_grid(. ~ name)
```










